services:
  - type: web
    name: elf-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn detection_flask:app"
    envVars:
      - key: FLASK_ENV
        value: production
